import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import ParentComponent from "./components/ParentComponent";
import { ThemeModeScript } from "flowbite-react";
import { HeroUIProvider } from "@heroui/system";

// Load Inter Variable Font Locally
const inter = localFont({
  src: "/fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  display: "swap",
});

// Load Syne Variable Font Locally
const syne = localFont({
  src: "/fonts/Syne-VariableFont_wght.ttf",
  variable: "--font-syne",
  display: "swap",
});

export const metadata: Metadata = {
  title: "CreatorsLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#161616] text-white">
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${inter.variable} ${syne.variable} antialiased w-full overflow-x-hidden max-w-[1440px] mx-auto px-4 md:px-10 lg:px-14`}
      >
        <HeroUIProvider>
          <ParentComponent>{children}</ParentComponent>
        </HeroUIProvider>
      </body>
    </html>
  );
}
