import type { Metadata } from "next";
import { Inter, Syne } from "next/font/google";
import "./globals.css";
import ParentComponent from "./components/ParentComponent";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const syne = Syne({ subsets: ["latin"], variable: "--font-syne" });

export const metadata: Metadata = {
  title: "CreatorsLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${syne.variable} antialiased w-full overflow-x-hidden`}
      >
        <ParentComponent>{children}</ParentComponent>
      </body>
    </html>
  );
}
